/*
 codigo, apellidos y nombres,edad cargo, sueldo basico, bono descuento
 areas
operario

sueldo basico 930
descuento 100

supervisor

sueldo basico 1500
bono 150
descuento 250

gerente

sueldo basico 7500
bono 1120
descuento 720
 */
package linkedlistzz;

import java.util.LinkedList;

/**
 *
 * @author LAB-USR-AQ265-A0302
 */
public class FormuLink extends javax.swing.JFrame {

    /**
     * Creates new form FormuLin
     */
    private String cod, apeynom, cargo;
    private int edad;
    private double sbasico, desc, bono;
    
    
    LinkedList<Empleado> elwe=new LinkedList<>();
    
    public FormuLink() {
        initComponents();
        
        posiblebono.setVisible(false);
            txtbono.setVisible(false);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        posiblebono = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        txtapeynom = new javax.swing.JTextField();
        txtedad = new javax.swing.JTextField();
        jccargo = new javax.swing.JComboBox<>();
        txtsbasico = new javax.swing.JTextField();
        txtbono = new javax.swing.JTextField();
        txtdesc = new javax.swing.JTextField();
        actgua = new javax.swing.JButton();
        actimp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        verdat = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("codigo");

        jLabel2.setText("apellidos y nombres");

        jLabel3.setText("edad");

        jLabel4.setText("cargo");

        jLabel5.setText("sueldo basico");

        posiblebono.setText("bono");

        jLabel7.setText("descuento");

        jccargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "operario", "supervisor", "gerente" }));
        jccargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jccargoActionPerformed(evt);
            }
        });

        actgua.setText("guardar");
        actgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actguaActionPerformed(evt);
            }
        });

        actimp.setText("imprimir datos");
        actimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actimpActionPerformed(evt);
            }
        });

        verdat.setColumns(20);
        verdat.setRows(5);
        jScrollPane1.setViewportView(verdat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtcod, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(txtapeynom)
                    .addComponent(txtedad)
                    .addComponent(jccargo, 0, 1, Short.MAX_VALUE))
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(posiblebono)
                            .addComponent(jLabel7))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtsbasico)
                            .addComponent(txtbono)
                            .addComponent(txtdesc, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(actgua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(actimp)
                        .addGap(119, 119, 119))))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsbasico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(posiblebono)
                    .addComponent(txtapeynom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jccargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(actgua)
                            .addComponent(actimp))))
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jccargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jccargoActionPerformed
        
        if(jccargo.getSelectedItem().toString().equalsIgnoreCase("operario")){
            posiblebono.setVisible(false);
            txtbono.setVisible(false);
        }else{
            posiblebono.setVisible(true);
            txtbono.setVisible(true);
        }
        
        
        
    }//GEN-LAST:event_jccargoActionPerformed

    private void actguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actguaActionPerformed
       
         
        cod=txtcod.getText();
        apeynom=txtapeynom.getText();
        cargo=jccargo.getSelectedItem().toString();
       edad= Integer.parseInt(txtedad.getText());
        
        sbasico=Double.parseDouble(txtsbasico.getText());
        if(cargo=="gerente"){
            
            bono=Double.parseDouble(txtbono.getText());
        }
        desc=Double.parseDouble(txtdesc.getText());
        
        
        if(cargo=="operario"){
            
            Operario nuevo=new Operario(cod, apeynom, cargo, edad, sbasico, desc);
            
            elwe.add(nuevo);
        }else{
            
            Gerente nuevo=new Gerente(cod, apeynom, cargo, edad, sbasico, desc, bono);
            
            elwe.add(nuevo);
        }
        
        
        limpiar();
        
    }//GEN-LAST:event_actguaActionPerformed

    private void actimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actimpActionPerformed
        
        
        for(Empleado e: elwe){
            
            System.out.println(e.toString());
            
            verdat.append(e.toString()+"\n");
        }
        
    }//GEN-LAST:event_actimpActionPerformed

    public void limpiar(){
        
        txtcod.setText("");
        txtapeynom.setText("");
        jccargo.setSelectedItem(0);
        txtedad.setText("");
        txtsbasico.setText("");
          
            txtbono.setText("");
        
        txtdesc.setText("");
    }
            
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormuLink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormuLink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormuLink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormuLink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormuLink().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actgua;
    private javax.swing.JButton actimp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jccargo;
    private javax.swing.JLabel posiblebono;
    private javax.swing.JTextField txtapeynom;
    private javax.swing.JTextField txtbono;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtdesc;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtsbasico;
    private javax.swing.JTextArea verdat;
    // End of variables declaration//GEN-END:variables
}
